name: CI guide

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: S3 Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        run:
          aws s3 cp \
          --recursive \
          --region ap-northeast-2
          dist s3://action-test